version: '2'

services:
  rancher:
    image: rancher/rancher:v2.7-head
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - "./rancher-data:/var/lib/rancher"
    privileged: true
    environment:
      - NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.10.0/24,.svc,.cluster.local,example.com
