services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
      - ~/.local:/home/coder/.local
      - ~/.config:/home/coder/.config
      - ~:/home/coder/project
    user: "1000:1001"
    environment:
      - DOCKER_USER=${USER}
    stdin_open: true
    networks:
      - proxy-network
    tty: true
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.codeserver.rule=Host(`code.desktop.madhur.co.in`)"
        - "traefik.http.routers.codeserver.entrypoints=web"
        - "traefik.http.services.codeserver.loadbalancer.server.port=8080"
        - "traefik.docker.network=proxy-network"
        - "traefik.http.routers.codeserver.middlewares=vpn-whitelist"
        - "traefik.http.middlewares.vpn-whitelist.ipwhitelist.sourcerange=10.42.42.0/24,192.168.1.0/24"

networks:
  proxy-network:
    external: true