
services:
  app:
    image: lissy93/networking-toolbox:latest
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nt.rule=Host(`nt.desktop.madhur.co.in`)"
      - "traefik.http.routers.nt.entrypoints=web"
      - "traefik.http.services.nt.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.nt.middlewares=vpn-whitelist"
      - "traefik.http.middlewares.vpn-whitelist.ipwhitelist.sourcerange=10.42.42.0/24,192.168.1.0/24"




networks:
  proxy-network:
    external: true