services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.madhur.co.in"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 127.0.0.1:8000:80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true