services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.madhur.co.in"
    volumes:
      - ./vw-data/:/data/
    # ports:
    #   - 127.0.0.1:8000:80
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.madhur.co.in`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letencrypt"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.vaultwarden.middlewares=vpn-whitelist"
      - "traefik.http.middlewares.vpn-whitelist.ipwhitelist.sourcerange=10.42.42.0/24,192.168.1.0/24"


networks:
  proxy-network:
    external: true