volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - INSECURE=true 
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      proxy-network: {}  # For Traefik access
      wg:  # For VPN network with static IPs
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      #- "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      # These labels route HTTPS traffic to the wg-easy WEB INTERFACE (port 51821)
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`wg.desktop.madhur.co.in`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.routers.wg-easy.tls.certresolver=letencrypt"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"
      - "traefik.docker.network=proxy-network"


networks:
  wg:
    name: wg 
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64


  proxy-network:
    external: true