services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Asia/Kolkata
    networks:
      - proxy-network
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443 # HTTPS entryPoints
      - 8081:8080 # Dashbaord WebGui 
      - "8082:8082" #metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik:/certs
      - ./letsencrypt:/letsencrypt  # Add this line

volumes:
  traefik:
    name: traefik


networks:
  proxy-network:
    external: true