services:
  watchtower:
    image: containrrr/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATION_URL=ntfy://ntfy:80/systemd?title=WatchtowerUpdates&scheme=http
      - WATCHTOWER_SCHEDULE=0 0 23 * * *
      - TZ=Asia/Kolkata
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true