services:
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    container_name: 'cadvisor'
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    # ports:
    #   - '808:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.desktop.madhur.co.in`)"
        - "traefik.http.routers.cadvisor.entrypoints=web"
        - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
        - "traefik.docker.network=proxy-network"
        - "traefik.http.routers.cadvisor.middlewares=vpn-whitelist"
        - "traefik.http.middlewares.vpn-whitelist.ipwhitelist.sourcerange=10.42.42.0/24,192.168.1.0/24"


networks:
  proxy-network:
    external: true