{
 "title": "Agamotto",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [ "services" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Throughput & Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$application\", uri !~ \"/actuator.*\", uri !~ \"/health.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "p99  response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(http_server_requests_seconds_bucket{job=\"$application\", uri !~ \"/actuator.*\", uri !~ \"/health.*\"}[1m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Throughput RPS",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{job=\"$application\", uri !~ \"/actuator.*\", uri !~ \"/health.*\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error rate RPS",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri)  (rate(http_server_requests_seconds_count{job=\"$application\", status!~\"2.*\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}