{
 "title": "Gauntlet - Graphite",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gauntlet- Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sum(stats.timers.gauntlet.*.count)"
    }
   ]
  },
  {
   "title": "Gauntlet - p99 Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.*.upper_99"
    }
   ]
  },
  {
   "title": "Kafka Consumer p99 latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.kafka.consumer.*.upper_99"
    }
   ]
  },
  {
   "title": "Kafka Consumer Message throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.kafka.consumer.*.count"
    }
   ]
  },
  {
   "title": "Gauntlet  Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.gauntlet.ex.*.rate"
    }
   ]
  },
  { "title": "Contest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Join pvt contest confirm - Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinPrivateContestConfirm.count"
    }
   ]
  },
  {
   "title": "Join pvt contest confirm - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinPrivateContestConfirm.upper_99"
    }
   ]
  },
  {
   "title": "Get contest details  - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getContestDetails.count"
    }
   ]
  },
  {
   "title": "Get contest details - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getContestDetails.upper_99"
    }
   ]
  },
  {
   "title": "Join - Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.join.count"
    }
   ]
  },
  {
   "title": "Join - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.join.upper_99"
    }
   ]
  },
  {
   "title": "Join pvt contest validate - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinPrivateContestValidate.count"
    }
   ]
  },
  {
   "title": "Join pvt contest validate - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinPrivateContestValidate.upper_99"
    }
   ]
  },
  {
   "title": "Get contests - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getContests.count"
    }
   ]
  },
  {
   "title": "Get contests - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getContests.upper_99"
    }
   ]
  },
  {
   "title": "Get Upcoming match contest - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUpcomingMatchContest.count"
    }
   ]
  },
  {
   "title": "Get Upcoming match contest - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUpcomingMatchContest.upper_99"
    }
   ]
  },
  {
   "title": "Get My Contests - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMyContests.count"
    }
   ]
  },
  {
   "title": "Get My Contests - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMyContests.upper_99"
    }
   ]
  },
  {
   "title": "Join validation - Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinValidation.count"
    }
   ]
  },
  {
   "title": "Join validation - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.joinValidation.upper_99"
    }
   ]
  },
  {
   "title": "Switch Team - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.switchTeam.count"
    }
   ]
  },
  {
   "title": "Switch Team - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.switchTeam.upper_99"
    }
   ]
  },
  {
   "title": "Get Match Squad - Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchSquad.count"
    }
   ]
  },
  {
   "title": "Get Match Squad - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchSquad.upper_99"
    }
   ]
  },
  { "title": "Matches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Get Matches - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatches.count"
    }
   ]
  },
  {
   "title": "Get Matches - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatches.upper_99"
    }
   ]
  },
  {
   "title": "Get Match players - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchPlayers.count"
    }
   ]
  },
  {
   "title": "Get Match players - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchPlayers.upper_99"
    }
   ]
  },
  {
   "title": "getAllMatchDetails - Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getAllMatchDetails.count"
    }
   ]
  },
  {
   "title": "getAllMatchDetails - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getAllMatchDetails.upper_99"
    }
   ]
  },
  {
   "title": "Get My Matches - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMyMatches.count"
    }
   ]
  },
  {
   "title": "Get My Matches - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMyMatches.upper_99"
    }
   ]
  },
  { "title": "Team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Get user teams - Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUserTeams.count"
    }
   ]
  },
  {
   "title": "Get user teams - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUserTeams.upper_99"
    }
   ]
  },
  {
   "title": "Update team - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.updateTeam.count"
    }
   ]
  },
  {
   "title": "Update team - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.updateTeam.upper_99"
    }
   ]
  },
  {
   "title": "Get user team details - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUserTeamDetails.count"
    }
   ]
  },
  {
   "title": "Get user team details - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUserTeamDetails.upper_99"
    }
   ]
  },
  {
   "title": "Get ultimate team - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUltimateTeam.count"
    }
   ]
  },
  {
   "title": "Get ultimate team - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getUltimateTeam.upper_99"
    }
   ]
  },
  {
   "title": "Save team - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.saveTeam.count"
    }
   ]
  },
  {
   "title": "Save team - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.saveTeam.upper_99"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Get Player Statistics - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getPlayerStatistics.count"
    }
   ]
  },
  {
   "title": "Get Player Statistics - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getPlayerStatistics.upper_99"
    }
   ]
  },
  {
   "title": "Get Invite Code Details - Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getInviteCodeDetails.count"
    }
   ]
  },
  {
   "title": "Get Invite Code Details - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getInviteCodeDetails.upper_99"
    }
   ]
  },
  {
   "title": "ScoreCard - Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchScoreCard.count"
    }
   ]
  },
  {
   "title": "ScoreCard - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getMatchScoreCard.upper_99"
    }
   ]
  },
  {
   "title": "Get Leaderboard - Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getLeaderBoard.count"
    }
   ]
  },
  {
   "title": "Get Leaderboard - p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.getLeaderBoard.upper_99"
    }
   ]
  },
  { "title": "External HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 } },
  {
   "title": "FMS Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.fms.*.count"
    }
   ]
  },
  {
   "title": "FMS p99 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.fms.*.upper_99"
    }
   ]
  },
  {
   "title": "UMS Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.ums.*.count"
    }
   ]
  },
  {
   "title": "UMS p99 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.ums.*.upper_99"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.nfs.*.count"
    }
   ]
  },
  {
   "title": "NFS p99 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.nfs.*.upper_99"
    }
   ]
  },
  {
   "title": "Moneta Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.moneta.*.count"
    }
   ]
  },
  {
   "title": "Moneta p99 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.moneta.*.upper_99"
    }
   ]
  },
  {
   "title": "Artemis Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.artemis.*.count"
    }
   ]
  },
  {
   "title": "Artemis p99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.artemis.*.upper_99"
    }
   ]
  },
  {
   "title": "Bonus Service Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.bonus_service.*.count"
    }
   ]
  },
  {
   "title": "Bonus Service max Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.bonus_service.*.upper_99"
    }
   ]
  },
  {
   "title": "Fantasy LB Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.fps.*.count"
    }
   ]
  },
  {
   "title": "Fantasy LB p99 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.gauntlet.http.external.fps.*.upper_99"
    }
   ]
  }
 ]
}